
language: java

jdk:
 - openjdk11
 
addons:
  sonarcloud:
    organization: "andreadepaolis95"
    token:
     secure: "SpHlGLZvLMCkL2Hp/5jmeLIl35pG631b85WvDkQX2jAHagFRFh8uzctKO+1oEV4YLpu5uLQl2Ui3v6Cp/x6uRE07nHl+rxVMSgBZGz74cGznFVSSuMb80YrNlRW7CoX/C5x3S+u0mizk4dt2VDnZywYRNevVHeQCyhA26q502NvRxnUHxsuzPAv+HFyPXJQu6KOu/A5a7E8Suq5dSS152g8YGmaGWFB4HopxX2UXf1N8gw7laGkGO2dhpM+yvewg5jL9r+DxSM8U0WzFZGq61gV7WS2cgNYp4pFykTfvGIxwFNhIdMJmaVGpUD2ZqRCejKTsoy4kL2llE4erMXGORDZmNQ4/ttbABEy94tUihDKGat0nO7ZykJgrjilsGiiCUx68NTdXiWmZsEQymiJdnx102sRXXQq7yUGJlz0nmGJ/M4OzaOlDwXmdAH88mH05ShkRnvHbA+0jBiRIGUjbG74PcKx3iyRWViR2Zam828uOvTrdIh7gDzHZFf0HsQo4N6g3UOtdtUVU62BuvNmLYQKiJD8vCdSsCr86G+gYUcOrtNWr4yd9ZJZK8vMAlZbSNyTiXKsfR2UF/0nayL5mmjE7aifxPhrzzF1X2SnyMojYZi9a+wVyYYvZ2F0tF4/GG1pCsUlkS7C91C1gqmaoqKwPH5vMRo7srN4OAwShVCk="

script:
  - ant build
  - sonar-scanner
 

  
