
language: java

jdk:
 - openjdk8
 
 
addons:
  sonarcloud:
    organization: "andreadepaolis95"
    token: 
      secure: "7f380050d3bcd8e0903f4260eed9a7d6c3f9325a"
      
script:
  - ant build
  - sonar-scanner
 

  
