
language: java

jdk:
 - openjdk11
 
addons:
  sonarcloud:
    organization: "andreadepaolis95"
    token:
      secure: "dlK3409Fs/YBnNhPSkTieyG8o1Gs8vzEr2ukzARpYG2qUnMMnpNUjQQecLQmxMft7iTpFiYt30taXBEg0fqV0q23PMV1xLg9426ay2A4Z/FQr3xh0jkGJe1O6eUbAbxVAAOifO2l2hSjFOaaooIc4GPFCyjGvFmtEB9jGmOfCxS6sUahhXe9RirSEOOG7ELwT5/VpK4kMPE4dNIV3HCdHm9GM9zM6BBvkwMcs7Ewb/nR1RSnaVuWwoWHzrGPDwMDGq0jMrKsnHxgwOpr+6EeUB3sDoBNvX/qkele8CBB9dFqXPfUcQTmV3sh3aY2MPylkpaxLzc6fqjIuu930nyirnwS+bbeozagtgX1ia+VLBdIzcN275O9KbcGOKiAgx/s7Dh1NXLTUOo5gP0goWQlzeHNejWMLlT14zgctay8c8wvtYD2acvcHW2t2ws7AJZS9RH9gEd+dyW3G1U5wcsbahYI7ecOuwgOLw19fPTvvlBqY/KCnUzF7WmEWLk5sRUHFopWi8puq3h70mdzFCQUNzEytSGBUNTlskWtbBR3Gq3i4AOKrdnhF5HqZeI3/eqsgRz4fo5wU88WVoWybIV4V3zQkKL65Y351tjOx6TFoV1S71S1P0cM6RzMxE9aeHbu7XBzhWzg0Qxw/1guyLpfpHTvP22PZ9DgV743qIWyUfI="

script:
  - ant build
  - sonar-scanner
 

  
