
language: java

jdk:
 - openjdk8
 
 
addons:
  sonarcloud:
    organization: andreadepaolis95
    token: 
      secure: 8fc156e7a8553c09ea2b7331bf8423a1a90f23d1
      
script:
  - ant build
  - sonar-scanner
 

  
