
language: java

jdk:
 - openjdk11
 
addons:
  sonarcloud:
    organization: "andreadepaolis95"
    token:
      secure: "KH6KqpgR20lqO55ue5F7UjMli8JNgKIQQkxjQH80nZnDkeCqnwFyITABK6xv3eYyedhfAjicFhtWIVcoWP7fC+M+7P5FBPlTibNe99QOGURVSzyVxD1be21bV3C4DYra2o7XPWiRBR4hPCYT7RRNyJ/zAVNuqFghD9Yx6vHB64uL39k67u7EnkKJUlLuSEt/zGi/xFfRYGEven2VukRIkDXlW4+WVIoq4X0+2oRsSuqmQ75DU1OdIvuu+tYxYWltC5ncMXr+h3xNFIZfsaEmezvyLmw5otFcqEAlcg7Vi/Gg/CLLCs9blRZ+xyJA5dmFpyJS/ZOotjpDFUIrXj0cC6WfiwVNnzYpjtbZcVu2e81BEmmhIwjDeBOZ4ZHJksU2Pragx+OyRvUFiGVmsSfUIeVf6uzXEgdcnZMDLA820BTKgDoAr9W3pul7JM0SDHNtdS14BiMhCow9rDcCrOjdWxG0PNB1DsIkaQJ7f3CYej7I3IorW7qTDmDHt8fNtT+6sRP9zIdh9jPUTPxx6fEPeadqZxXWZrCErJKSqQQkAkXTU7sMWiOxkVlI40vlXx21ooqHDHT0iMI6xWab/uiKZlhVRSPwvyi1U43RMg48NvaG8QUU8rofaF5qIEEfAJux9MoAr6lQ0pDJv0xl7EAu9cOMCZ7jW5O/IyTW8WL3J7c="

script:
  - ant build
  - sonar-scanner
 

  
